### ISSUE TITLE
bbnorm.sh not found

### ISSUE THREAD

**Issue by asifzubair** [arundurvasula/coverage-depth-assembly#1]
Hi @arundurvasula ,

I was trying to see how you did the normalization and it seems you used a `bbnorm.sh` script which I can't find in the repo. Would you mind pushing it ?

Thank you,
Best, 

Asif

**Comment by arundurvasula** [comment]
Hi Asif,
The `bbnorm.sh` script is from the BBMap package and you should be able to get it from there. Let me know if you run into any issues!

[Announcement](http://seqanswers.com/forums/showthread.php?t=49763) 
[Package](https://sourceforge.net/projects/bbmap/)

**Comment by asifzubair** [comment]
Thanks, Arun!
